def generate_report(target, results):
    """
    Generate a text-based report for the scan results.
    """
    report_lines = []
    report_lines.append("SecurePort Scanner Report")
    report_lines.append("=" * 40)
    report_lines.append(f"Target: {target}")
    report_lines.append("")

    if results:
        report_lines.append("Open Ports:")
        for port, status in results:
            report_lines.append(f" - Port {port}: {status}")
    else:
        report_lines.append("No open ports detected.")

    report_lines.append("")
    report_lines.append("Report generated by SecurePort Scanner.")
    return "\n".join(report_lines)
